### ISSUE TITLE
The operation has timed out

### ISSUE THREAD

**Issue by armandfrigo** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#31]
Hi,
Is there any possibilty to increase the timeout value when checking for failed tasks?
We happen to have 3005 task at the moment in production.
When the servers are busy I can imagine that they don't respond immediately to REST API calls.
The check for failed tasks runs every 15 minutes and returns a successful value 1 time out of 4-6.
Which means that we check for failed tasks every 15 minutes and we receive alerts every 60 to 90 minutes.

Error message:
Time, LogLevel, Message
2022_04_05_11_30_02,Information,"Proxy: https://localhost"
2022_04_05_11_30_04,Information,"Looking for Failed Tasks..."
2022_04_05_11_31_04,Error,"System.Exception: Timeout: The operation has timed out
   at QVnextDemoBuilder.QRSNTLMWebClient.Get(String endpoint, Dictionary`2 queries)
   at QlikSenseJSONObjects.QlikSenseJSONHelper.GetDeletedUserList(QSTaskStatus status)
   at QlikSenseEmailAdmin.Program.Main(String[] args)
"
2022_04_05_11_31_04,Information,"Returning Errorlevel 8"

**Comment by armandfrigo** [comment]
I have fixed this by increasing the timeout value.

**Comment by Amarender-Mokalla** [comment]
Hi @armandfrigo @NickAkincilar ,
I am facing the same issue "Operation has timed out ". Could you please help me in fixing it.
I even tried above solution by increasing the timeout value but issue remains still same
