### ISSUE TITLE
Array error

### ISSUE THREAD

**Issue by micahsakata** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#8]
I got everything to work. I can see in the log that it's detecting failures. But then it errors on an array. I'm running QS 3.1.3. Any thoughts?

Time, LogLevel, Message 
2017_06_28_02_52_28,Information,"Proxy: [myserver]" 
2017_06_28_02_52_28,Information,"Looking for Failed Tasks..." 
2017_06_28_02_52_28,Information,"Found 9 Failed Tasks!" 
2017_06_28_02_52_28,Error,"System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) at System.Collections.Generic.List`1.get_Item(Int32 index) at QlikSenseEmailAdmin.Program.Main(String[] args)" 
2017_06_28_02_52_28,Information,"Returning Errorlevel 8"

**Comment by FanHung** [comment]
Hi,
I got the same issue, please could you let me know how to fix this issue? Thank you.

**Comment by NickAkincilar** [comment]
@FanHung 
Could please you upload send history and log files?

**Comment by FanHung** [comment]
Hi Nick,

Thank you for your reply.
I have attached the log files for your reference.
The send history log is empty, I don't attach it.

[QlikSenseTasklog.zip](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/1209957/QlikSenseTasklog.zip)

**Comment by NickAkincilar** [comment]
@FanHung  Could you also be able to send screenshots:

1.  Tools Config screen on the tool (not the password) 

2. Screenshot of the Tasks List in QMC showing the Status of the failed task after you click on the "i" icon next to Failed status which displays task details.

**Comment by FanHung** [comment]
Hi Nick,

I have attached the file which includes the screenshots for your reference. Thank you.


[Screenshot of Tools and Error Log.docx](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/1211164/Screenshot.of.Tools.and.Error.Log.docx)

**Comment by NickAkincilar** [comment]
@micahsakata @FanHung  Just uploaded 1.4b version. Error should be fixed now. Please try and let me know if problem goes away.

**Comment by FanHung** [comment]
Hi Nick,

Thank you for your quick response.
I re-installed the new version (1.4b), however, new issue has raised.
I attached the log file for your reference.
Thanks again for your kindly help.

[QlikSenseTasklog_2017_08_09_10_22_30.zip](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/1211710/QlikSenseTasklog_2017_08_09_10_22_30.zip)

**Comment by NickAkincilar** [comment]
This error is most likely for Email login/password issue. Please reenter user/password for your email and click on TEST button to make sure it can send it.

**Comment by FanHung** [comment]
Hi Nick,

I can send the mail via TEST button, however, the issue still exists.
You can refer to the attached file.
Thanks for your help.

[Screenshot of Sending Mail and Error Log.docx](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/1213317/Screenshot.of.Sending.Mail.and.Error.Log.docx)
